baseURL = 'https://farzadhayat.vercel.app/'
languageCode = 'en-us'
title = 'Farzad Hayat'
theme = 'PaperMod'

[params.homeInfoParams]
Title = "Hi there 👋"
Content = """>
	Second-year **Computer Science** student at **Queensland University of Technology**.
       	Seeking a Software Engineering or related internship in Australia or New Zealand for the 2023 summer holiday.
       	In my free time, I enjoy exploring open source software, rock climbing, latin dancing, and motorcycling."""

[[params.socialIcons]]
name = "Email"
url = "mailto:farzad.hayat@outlook.com"

[[params.socialIcons]]
name = "GitHub"
url = "https://github.com/FarzadHayat"

[[params.socialIcons]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/farzad-hayat/"

[[params.socialIcons]]
name = "Resume"
url = "https://farzadhayat.github.io/portfolio/FARZAD_HAYAT_Resume.pdf"


