baseURL = 'https://farzadhayat.github.io/portfolio'
languageCode = 'en-us'
title = 'Farzad Hayat'
theme = 'PaperMod'

[params.homeInfoParams]
Title = "Hi there 👋"
Content = """>
I am a second-year **Computer Science** student at **Queensland University of Technology**. Currently seeking a Software Engineering or related internship in Australia or New Zealand for the 2023 summer holiday. In my free time, I enjoy exploring open source software, latin dancing, and motorcycling."""

[[params.socialIcons]]
name = "Email"
url = "mailto:farzad.hayat@outlook.com"

[[params.socialIcons]]
name = "GitHub"
url = "https://github.com/FarzadHayat"

[[params.socialIcons]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/farzad-hayat/"

[[params.socialIcons]]
name = "Resume"
url = "https://farzadhayat.github.io/portfolio/resume.pdf"


