baseURL = 'http://hayatbakhsh.xyz/'
languageCode = 'en-us'
title = 'My Portfolio'
theme = 'PaperMod'

[params.homeInfoParams]
Title = "Hi there wave"
Content = "Can be Info, links, about..."

[[params.socialIcons]]
name = "Email"
url = "mailto:farzad.hayatbakhsh@outlook.com"

[[params.socialIcons]]
name = "GitHub"
url = "https://github.com/FarzadHayat"
